name: lsptest
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  lsp_server: ^0.4.0
  json_rpc_2: any

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
